### ISSUE TITLE
Integrate Username/Password Validation

### ISSUE THREAD

**Issue by benjic** [orbitable/mission-control#27]
With a valid authentication endpoint it should be possible to validate a given username password combination.

Acceptance Criteria 
===================
- [x] There should be a user model with a username and password
- [x] There should be a few fixture users to test logins with
- [x] A request with valid credentials should return a mock token
- [x] A request with invalid credentials should return an error with `403 Forbidden`.

**Comment by dill-wood** [comment]
I will look into this and create a PR soon!
